### ISSUE TITLE
add dependency to package `frontend`

### ISSUE THREAD

**Issue by monperrus** [kastman/fitz#4]
The PIP package should have a dependency to package `frontend`, otherwise:

```
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
    import fitz
  File "/home/martin/.local/lib/python3.8/site-packages/fitz/__init__.py", line 1, in <module>
    from frontend import *
ModuleNotFoundError: No module named 'frontend'
```

**Comment by kastman** [comment]
Hi @monperrus - Thanks for the comment. This seems to be a problem with the way that py3 imports libraries; when fitz was last being actively developed py2 wasn't deprecated. 

I'd welcome a fixing PR if you'd like, or I can try to take a look but it may be some time before I can look at it.

**Comment by monperrus** [comment]
ack, thanks.

**Comment by KevinAlexandro** [comment]
Any solution for this issue besides deprecating the version installed?

**Comment by kastman** [comment]
Sorry @KevinAlexandro - Fitz really isn't maintained any more. You'd be better off using another alternative (fmriprep is another good nipype-based workflow with a much larger user base) unless you have a specific reason to roll your own.
