### ISSUE TITLE
about source

### ISSUE THREAD

**Issue by tongchangD** [kastman/fitz#6]
Is your source from a C++ compiler

I see `_fitz.cpython-37m-x86_64-linux-gnu.so` file appearing after `pip Install fitz` or `pip install PyMuPDF`.

How to generate or use it

Looking forward to your reply

**Comment by kastman** [comment]
Sorry, but this project is for an imaging analysis pipeline.

I think the repository you want is actually here: https://github.com/pymupdf/PyMuPDF
